version: 2
jobs:
  build:
    docker:
      - image: quay.io/mojanalytics/docker-data-linter
    steps:
      - checkout
      - run:
          name: setup env
          command: |  # use pipenv to install dependencies
            sudo pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            python -m unittest discover
