version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install -r requirements.txt
      - run:
          name: Running tests
          command: |
            python -m unittest discover
