name: Python package

on:
  [push]

jobs:
  build:

    runs-on: python:3.7-slim

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            python -m unittest discover tests/
